In [2]:
import pandas as pd
import pyarrow.parquet as pq
import connectorx as cx
from io import StringIO

In [3]:
a_file = 'mt4_uk8-2023-510208161.parquet'
table= pq.read_table(a_file)
df = table.to_pandas()
df

,login,trade_date,server_id,today_deposit,today_withdrawal,balance,today_closed_pnl,total_unrealized_pnl,current_credit,equity,...,ytd_pnl_delta,total_30d_pnl_delta,t_m2_pnl_delta,t_m3_pnl_delta,t_m4_pnl_delta,t_m5_pnl_delta,t_m6_pnl_delta,t_m7_pnl_delta,num_pos_pnl_delta_past_7_days,total_7d_pnl_delta
0,510208161,2023-06-07,49,534.9575,0.0,534.957500,0.000000,0.000000,0.0,534.957500,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000
1,510208161,2023-06-08,49,0.0000,0.0,550.352709,11.235209,0.625376,0.0,550.978085,...,11.860585,11.860585,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,11.860585
2,510208161,2023-06-09,49,0.0000,0.0,554.353454,5.718308,0.000000,0.0,554.353454,...,16.953517,16.953517,11.860585,0.000000,0.000000,0.000000,0.000000,0.000000,2,16.953517
3,510208161,2023-06-10,49,0.0000,0.0,554.353454,0.000000,0.000000,0.0,554.353454,...,16.953517,16.953517,5.092932,11.860585,0.000000,0.000000,0.000000,0.000000,2,16.953517
4,510208161,2023-06-11,49,0.0000,0.0,554.353454,0.000000,0.000000,0.0,554.353454,...,16.953517,16.953517,0.000000,5.092932,11.860585,0.000000,0.000000,0.000000,2,16.953517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,510208161,2023-09-09,49,0.0000,0.0,783.466393,0.000000,0.000000,0.0,783.466393,...,264.357150,117.608525,3.402294,8.135920,4.183798,15.165914,6.423501,0.000000,5,37.311426
95,510208161,2023-09-10,49,0.0000,0.0,783.466393,0.000000,0.000000,0.0,783.466393,...,264.357150,116.108001,0.000000,3.402294,8.135920,4.183798,15.165914,6.423501,5,37.311426
96,510208161,2023-09-11,49,0.0000,0.0,804.728678,17.630820,-0.473022,0.0,804.255655,...,281.514948,133.265799,0.000000,0.000000,3.402294,8.135920,4.183798,15.165914,5,48.045723
97,510208161,2023-09-12,49,0.0000,0.0,812.490564,7.484923,-0.774302,0.0,811.716262,...,288.698590,140.449442,17.157798,0.000000,0.000000,3.402294,8.135920,4.183798,5,40.063453
98,510208161,2023-09-13,49,0.0000,0.0,819.822725,9.205825,1.845457,0.0,821.668181,...,300.524175,127.552031,7.183643,17.157798,0.000000,0.000000,3.402294,8.135920,5,47.705239

In [10]:
# filtered_df = df[
#     (df['today_closed_pnl'] != 0) &
#     (df['today_deposit'] != 0 ) &
#     (df['today_swaps'] != 0 ) &
#     (df['total_deposit'] != df['today_deposit'])]
filtered_df = df[df['login'] == 3001153]
filtered_df.tail(20)

,login,trade_date,server_id,today_deposit,today_withdrawal,balance,today_closed_pnl,total_unrealized_pnl,current_credit,equity,...,ytd_pnl_delta,total_30d_pnl_delta,t_m2_pnl_delta,t_m3_pnl_delta,t_m4_pnl_delta,t_m5_pnl_delta,t_m6_pnl_delta,t_m7_pnl_delta,num_pos_pnl_delta_past_7_days,total_7d_pnl_delta
69,510208161,2023-08-15,49,0.0,0.0,739.982753,17.461787,1.145214,0.0,741.127967,...,191.699106,24.606116,24.722995,0.000000,0.000000,1.500524,7.973550,15.693864,5,68.617897
70,510208161,2023-08-16,49,0.0,0.0,741.924743,3.807755,0.000000,0.0,741.924743,...,194.361647,12.820254,18.726962,24.722995,0.000000,0.000000,1.500524,7.973550,5,55.586573
71,510208161,2023-08-17,49,0.0,0.0,756.758618,15.297608,-3.229133,0.0,753.529485,...,206.430122,278.001766,2.662541,18.726962,24.722995,0.000000,0.000000,1.500524,5,59.681498
72,510208161,2023-08-18,49,0.0,0.0,759.925621,3.153083,0.000000,0.0,759.925621,...,212.812338,274.426159,12.068475,2.662541,18.726962,24.722995,0.000000,0.000000,5,64.563189
75,510208161,2023-08-21,49,0.0,0.0,777.226535,15.689880,-28.982695,0.0,748.243840,...,199.519523,239.456061,0.000000,0.000000,6.382216,12.068475,2.662541,18.726962,4,26.547379
76,510208161,2023-08-22,49,0.0,0.0,728.357187,-45.302698,-1.616017,0.0,726.741170,...,181.583503,221.520042,-13.292815,0.000000,0.000000,6.382216,12.068475,2.662541,3,-10.115603
77,510208161,2023-08-23,49,0.0,0.0,735.365816,5.779675,0.000000,0.0,735.365816,...,188.979195,215.483127,-17.936020,-13.292815,0.000000,0.000000,6.382216,12.068475,3,-5.382453
78,510208161,2023-08-24,49,0.0,0.0,743.708347,11.967223,-1.708059,0.0,742.000288,...,199.238359,217.509482,7.395691,-17.936020,-13.292815,0.000000,0.000000,6.382216,3,-7.191763
79,510208161,2023-08-25,49,0.0,0.0,747.825066,5.128005,0.000000,0.0,747.825066,...,206.074423,216.202343,10.259164,7.395691,-17.936020,-13.292815,0.000000,0.000000,3,-6.737915
82,510208161,2023-08-28,49,0.0,0.0,754.412356,4.976763,-0.703238,0.0,753.709118,...,210.347948,195.972955,0.000000,0.000000,6.836064,10.259164,7.395691,-17.936020,4,10.828425
83,510208161,2023-08-29,49,0.0,0.0,765.175673,6.506300,-5.450930,0.0,759.724743,...,212.106556,197.731563,4.273525,0.000000,0.000000,6.836064,10.259164,7.395691,5,30.523053
85,510208161,2023-08-31,49,0.0,0.0,772.103971,9.488238,0.000000,0.0,772.103971,...,227.045723,170.556104,-9.077458,1.758608,4.273525,0.000000,0.000000,6.836064,4,27.807364
89,510208161,2023-09-04,49,0.0,0.0,760.002728,7.136024,-0.712523,0.0,759.290206,...,233.469224,148.794489,0.000000,0.000000,0.000000,24.016626,-9.077458,1.758608,3,23.121277
90,510208161,2023-09-05,49,0.0,0.0,768.999734,14.185338,0.268053,0.0,769.267787,...,248.635138,163.960402,6.423501,0.000000,0.000000,0.000000,24.016626,-9.077458,3,36.528582
91,510208161,2023-09-06,49,0.0,0.0,772.412109,3.035840,1.416010,0.0,773.828120,...,252.818936,147.228352,15.165914,6.423501,0.000000,0.000000,0.000000,24.016626,4,49.789838
92,510208161,2023-09-07,49,0.0,0.0,781.161743,10.974558,-1.422628,0.0,779.739116,...,260.954855,137.873646,4.183798,15.165914,6.423501,0.000000,0.000000,0.000000,4,33.909132
93,510208161,2023-09-08,49,0.0,0.0,783.466393,1.979666,0.000000,0.0,783.466393,...,264.357150,125.582076,8.135920,4.183798,15.165914,6.423501,0.000000,0.000000,5,37.311426
96,510208161,2023-09-11,49,0.0,0.0,804.728678,17.630820,-0.473022,0.0,804.255655,...,281.514948,133.265799,0.000000,0.000000,3.402294,8.135920,4.183798,15.165914,5,48.045723
97,510208161,2023-09-12,49,0.0,0.0,812.490564,7.484923,-0.774302,0.0,811.716262,...,288.698590,140.449442,17.157798,0.000000,0.000000,3.402294,8.135920,4.183798,5,40.063453
98,510208161,2023-09-13,49,0.0,0.0,819.822725,9.205825,1.845457,0.0,821.668181,...,300.524175,127.552031,7.183643,17.157798,0.000000,0.000000,3.402294,8.135920,5,47.705239

In [4]:
df.iloc[255]

login                                   3001153
trade_date                           2023-09-13
today_deposit                               0.0
today_withdrawal                            0.0
server_id                                    32
balance                          1376893.975498
today_closed_pnl                   -3200.464511
total_unrealized_pnl             -141756.673892
current_credit                              0.0
equity                           1235137.301606
today_swaps                         -908.669325
today_volume_usd_done                 15.732865
total_commission                    -199.807373
total_deposit                     954837.622434
total_realized_pnl                452293.381773
total_swaps                      -169663.664077
total_withdrawal                            0.0
t_m1_pnl_delta                    -16065.475688
historical_pnl                    310536.707881
mtd_pnl_delta                     -27850.145555
mtd_realized_pnl                    3516.540128
mtd_withdrawal                              0.0
total_30d_pnl_delta               -70585.578351
wtd_pnl_delta                     -11245.064871
ytd_pnl                            62473.135722
ytd_pnl_delta                     -24068.282885
t_m2_pnl_delta                     -1549.549506
t_m3_pnl_delta                      6368.252454
t_m4_pnl_delta                         1.707869
t_m5_pnl_delta                     -2259.648344
t_m6_pnl_delta                     -3609.782854
t_m7_pnl_delta                      8791.335422
num_pos_pnl_delta_past_7_days                 3
total_7d_pnl_delta                 -8323.160647
Name: 255, dtype: object

In [7]:
#Output sl data
selected_row = df.iloc[255:256]
row_table = selected_row.to_string(index=False, header=True, justify='left')
row_df = pd.read_csv(StringIO(row_table), delimiter='\s+')
row_df.to_excel("output_excel_file5.xlsx", index=False)

In [17]:
#EQUITY
mysql_url = "mysql://DataMY_read:qeC18ub3n3@192.168.1.179:3306/brad"
xlogin = input('Login: ')
xdate = input('Date: (yyyy-mm-dd)')
query = f"""
SELECT login, date, coalesce(balance*(equity_in_usd/equity),0)AS balance, equity_in_usd AS equity , coalesce(close_pnl*(equity_in_usd/equity ),0) AS ClosePNL , coalesce(floating_pnl*(equity_in_usd/equity),0 )AS FloatingPNL  , credit_in_usd, floating_pnl *(equity_in_usd/equity) AS unrealized_pnl, (close_pnl*(equity_in_usd/equity)+ unrealize_pnl*(equity_in_usd/equity))  as Historical_pnl
FROM brad.bbook_v_1_2021
where db = 'VUK8'
and login = {xlogin}
and `date` = '{xdate}'
"""
db1 = cx.read_sql(mysql_url, query)


#VFX
mysql_url = "mysql://DataMY_read:qeC18ub3n3@192.168.1.179:3306/vfx-vig"
query = f"""
SELECT deposit, withdrawal, (m_swap + s_swap) AS today_swap, (m_volume+s_volume)*2 as today_volume, (m_commission + s_commission) AS today_commission
FROM `vfx-vig`.detail d 
where db = 'VUK8'
and login = {xlogin}
and `date` = '{xdate}'
"""
db2 = cx.read_sql(mysql_url, query)


# #OUTPUT
pd.set_option('display.width', 1000)
combined_db = pd.concat([db1, db2], axis = 1)
print(combined_db)

Empty DataFrame
Columns: [login, date, balance, equity, ClosePNL, FloatingPNL, credit_in_usd, unrealized_pnl, Historical_pnl, deposit, withdrawal, today_swap, today_volume, today_commission]
Index: []

In [2]:
import pandas as pd
from datetime import datetime, timedelta

In [4]:
x = datetime.today().date()
x = x-timedelta(days = 1)
x = x.strftime('%Y-%m-%d')
x

'2024-01-17'